### ISSUE TITLE
Increase size of some of the free text edition boxes

### ISSUE THREAD

**Issue by cacereslab** [caceres-lab/InvFEST-code#36]
Some of the boxes to add free text are very small and it's difficult to read the whole text added. these include the boxes of:
- "Comments" box in New validation section
- "Description" box in Manually curated breakpoints section
- "Effect" and "Functional consequences" boxes for adding Genomic functional effects
- "Effect" box for adding Phenotypic functional effects

**Comment by RuthGG** [comment]
I think that this is already solved, because the lower right corner of all the free text boxes can be dragged to make the box bigger. 
![image](https://user-images.githubusercontent.com/22767844/37511183-2e6467ea-28fe-11e8-9412-0034daf91e25.png)
