### ISSUE TITLE
[Frequency map] Random placement of unknown populations

### ISSUE THREAD

**Issue by emsanz** [caceres-lab/InvFEST-code#37]
Unkown populations ara placed randomly at the bottom-left of the map and that's confusing.
The populations with unkown placment (but known region), are placed randomly in the specific region.

STEPS:
1. Give coordinates to each population.
2. Draw a square at the bottom-left of the map where unkown populations can be placed.

**Comment by cacereslab** [comment]
Currently all populations have an assigned position in the map and any new population should be assigned specific coordinates to avoid this problem.
