### ISSUE TITLE
Add "Prediction Study" filter to the search bar

### ISSUE THREAD

**Issue by cginer** [caceres-lab/InvFEST-code#40]
It would be nice to be able to filter inversions by prediction source. Similarly to the "Validation Study" filter already available.

**Comment by RuthGG** [comment]
Only 'Prediction study' or also 'Prediction method' ?

**Comment by cacereslab** [comment]
Maybe just prediction study? (unless creating both options is relatively simple)

**Comment by RuthGG** [comment]
There have been incorporated 3 new filters to the search bar: 
- Prediction Study
- Prediction Method
- Prediction Name (e.g. CINV_delly_INV00000339)
