### ISSUE TITLE
Public vs. Private report

### ISSUE THREAD

**Issue by RuthGG** [caceres-lab/InvFEST-code#48]
Predictions are not being displayed in the inversion reports if the user is not logged in. 
In addition, the ' Prediction type' field (Simple or Complex) in the General Information section is giving false information if the user is not logged in: because the public database does not have the 'Complexity' column in the inversions table the query was modified to not ask for the complexity information, meaning that in the inversion report it is always marked as 'Simple' (by default).

**Comment by RuthGG** [comment]
To solve the Complex-Simple problem, if the user is not logged in, the number of validations is given (as it was before we introduced the 'Prediction type' field). If the user is logged in, the number of validations is replaced by the complexity information. However, I consider this only a temporary solution because I'm not sure if Mario prefers to add the complexity column to the public database.

**Comment by cacereslab** [comment]
Yes, I think it's better to add the complexity column to the public database, since that is the inversion model we are going to use in the future (and also is another improvement to mention  in the InvFEST 2.0 paper).

**Comment by RuthGG** [comment]
As in the Complex-simple case, the problem with predictions not being shown was that the 'prediction_name' column in 'predictions' is not available in the private database. I applied the same temporary solution as in the other case, until the public database has both columns.

**Comment by RuthGG** [comment]
The two new columns and the information related to inversions available in the public database have been added. The temporary solution has been reverted because it is not necessary anymore. Now prediction names and complexity information will be visible both in public and private versions.
